[package]
name = "smithay-client-toolkit"
version = "0.6.4"
authors = ["Victor Berger <victor.berger@m4x.org>"]
documentation = "https://smithay.github.io/client-toolkit"
repository = "https://github.com/smithay/client-toolkit"
license = "MIT"
edition = "2018"
categories = ["gui"]
keywords = ["wayland", "client"]
description = "Toolkit for making client wayland applications."

[badges]
travis-ci = { repository = "smithay/client-toolkit" }

[dependencies]
bitflags = "1.0"
nix = "0.16"
dlib = "0.4"
lazy_static = "1.0"
memmap = "0.7"
andrew = "0.2.0"
wayland-client = { git = "https://github.com/Smithay/wayland-rs" }
wayland-protocols = { git = "https://github.com/Smithay/wayland-rs" , features = ["client", "unstable_protocols"] }
wayland-cursor = { git = "https://github.com/Smithay/wayland-rs" }
calloop = { git = "https://github.com/Smithay/calloop" }

[dev-dependencies]
image = "0.22"
wayland-client = { git = "https://github.com/Smithay/wayland-rs", features = ["dlopen"] }
byteorder = "1.0"
