[package]
name = "smithay-client-toolkit"
version = "0.8.1"
authors = ["Victor Berger <victor.berger@m4x.org>"]
documentation = "https://smithay.github.io/client-toolkit"
repository = "https://github.com/smithay/client-toolkit"
license = "MIT"
edition = "2018"
categories = ["gui"]
keywords = ["wayland", "client"]
description = "Toolkit for making client wayland applications."

[badges]
travis-ci = { repository = "smithay/client-toolkit" }

[dependencies]
bitflags = "1.0"
nix = "0.17"
dlib = "0.4"
lazy_static = "1.0"
memmap = "0.7"
andrew = { version = "0.2.0", optional = true }
log = "0.4"
wayland-client = "0.26"
wayland-protocols = { version = "0.26" , features = ["client", "unstable_protocols"] }
wayland-cursor = "0.26.1"
calloop = { version = "0.5", optional = true }
byteorder = "1.0"

[features]
default = ["frames", "calloop"]
frames = ["andrew"]

[dev-dependencies]
image = "0.22"
wayland-client = { version = "0.26", features = ["dlopen"] }
