[package]
name = "smithay-client-toolkit"
version = "0.1.0"
authors = ["Victor Berger <victor.berger@m4x.org>"]

[dependencies]
bitflags = "1.0"
dlib = "0.4"
lazy_static = "1"
memmap = "0.6"
tempfile = "3.0"
wayland-commons = { version = "0.20" }
wayland-client = { version = "0.20", features = ["cursor"] }
wayland-protocols = { version = "0.20", features = ["client"] }

[dev-dependencies]
wayland-client = { version = "0.20", features = ["dlopen"] }
byteorder = "1.0"

